Дополнения ко второму заданию.
htmlacademy-javascript/1463321-keksobooking-21 pull request #3
Opened 2020-10-19 17:08 UTC by Svetlana-Orlova

По какой-то причине все ранее внесённые изменения не подтянулись, поэтому сначала скопировала ранние задания и дополнила новым. Сменила редактор на VS Code.

2020-10-20 06:45 UTC, babtshe requested changes

2020-10-20 06:45 UTC, babtshe commented on index.html
> +</html>
стоит вернуть пустую строку

2020-10-20 06:45 UTC, babtshe commented on js/main.js
> +const photoTemplate = document.querySelector(`#card`).content.querySelector(`.popup__photo`);
стоит переиспользовать ссылку на элемент вместо повторного поиска.

2020-10-20 06:45 UTC, babtshe commented on js/main.js
> +  function createCardImages(photos) {
хорошо будет назвать функцию таким образом, чтобы сразу понимать, что она возвращает элементы карточек. Сейчас совсем не очевидно, что функция не создаёт элементы в DOM-дереве, а возвращает фрагмент с элементами.

2020-10-20 06:45 UTC, babtshe commented on js/main.js
> +  }
будет здорово постепенно привести циклы в соответствие с [критерием](https://up.htmlacademy.ru/javascript/21/criteries#d26)

2020-10-20 06:45 UTC, babtshe commented on js/main.js
> +    cardElement.querySelector(`.popup__text--capacity`).textContent = ad.offer.rooms + ` комнаты для ` + ad.offer.guests + ` гостей`;
есть смысл сделать так, чтобы окончания слов подстраивались под количество комнат и гостей.

2020-10-20 14:41 UTC, Svetlana-Orlova commented on js/main.js
> +  }
Не совсем поняла суть этого критерия.  Можно перебирать элементы массива как это сделала я. Можно перебирать их с помощью forEach, вложив внутрь те же данные. В интернете предлагают конструкцию for...of.  И окончательный вид будет примерно такой (вместо 84-88 строки): 
for (let i of photos) {
      let imgTemplate = photoTemplate.cloneNode(true);
      imgTemplate.src = photos[i];
      fragment.appendChild(imgTemplate);
    }

или 

photos.forEach(function (photo) {
      let imgTemplate = photoTemplate.cloneNode(true);
      imgTemplate.src = photo;
      fragment.appendChild(imgTemplate);
    })
Так? Если да, то переделаю циклы, где перебираются массивы, под этот формат.

2020-10-20 15:40 UTC, Svetlana-Orlova commented on js/main.js
> +  function createCardImages(photos) {
Переделала чуть-чуть на другое название. Так как конкретно в этой функции перебирается определённый массив из фотографий и константы в них тоже связаны с изображениями, не меняла photos на elements.

2020-10-21 06:42 UTC, babtshe commented on js/main.js
> +  }
В первом варианте в `i` будет элемент массива, а не индекс. Поэтому в этой строке будет ошибка: `imgTemplate.src = photos[i];`

2020-10-21 06:50 UTC, babtshe approved these changes

2020-10-21 06:50 UTC, babtshe commented on js/main.js
> +    if (rooms > 1 && rooms < 5 || rooms > 21 && rooms < 25) {
для текущего проекта такое решение будет работать, так как у нас ограничено максимальное количество комнат и гостей. Для практики есть смысл придумать решение для неограниченного количества. Для решения этой задачи пригодится определение остатка от деления с помощью `%`.

2020-10-21 06:50 UTC, babtshe commented on js/main.js
> +  function returnCardImages(photos) {
Стоит придерживаться единообразия в названиях переменных и функций. Где-то используется `get` а где-то `return`, хотя результат аналогичный.

2020-10-21 06:50 UTC, merged