Разбиение на модули
htmlacademy-javascript/1463321-keksobooking-21 pull request #6
Opened 2020-11-06 12:54 UTC by Svetlana-Orlova

2020-11-07 06:59 UTC, babtshe requested changes

2020-11-07 06:59 UTC, babtshe commented on js/card.js
> +  };
См [критерий](https://up.htmlacademy.ru/javascript/21/criteries#d3)

2020-11-07 06:59 UTC, babtshe commented on js/card.js
> +      window.pin.disablePin();
должен ли модуль карточки знать об устройстве пинов? Возможно будет лучше передать функцию для деактивации конкретной метки через коллбек.

2020-11-07 06:59 UTC, babtshe commented on js/data.js
> +  const MAX_Y = 630;
порядок констант

2020-11-07 06:59 UTC, babtshe commented on js/data.js
> +  };
такие константы есть смысл хранить в модуле, в котором они используются.

2020-11-07 06:59 UTC, babtshe commented on js/mainPin.js
> +  };
если значение вычисляется в ходе выполнения программы, это уже не константа.

2020-11-07 06:59 UTC, babtshe commented on js/mainPin.js
> +  }
этот модуль слишком много знает об устройстве формы с адресом.

2020-11-07 06:59 UTC, babtshe commented on js/map.js
> +  }
`forEach`

2020-11-09 03:51 UTC, Svetlana-Orlova commented
Непонятная мне ошибка от npm test: 
C:\Users\PC\Desktop\keksobooking\js\pin.js
  26:5  error  Function 'getPin' expected no return value      consistent-return

Не могу разобраться с поведением главного пина после отправки формы (убегает от курсора). Почему дважды навешивается на кнопку `mousedown`  и посредством remove(`mousedown` cb)  это не исправляется? Я пыталась отмену повесить непосредственно перед выполнением движений мышкой - безуспешно.

2020-11-10 13:53 UTC, babtshe requested changes

2020-11-10 13:53 UTC, babtshe commented on js/filter.js
> +  }
судя по названию, функция записывает цену, а на самом деле возвращает результат проверки.

2020-11-10 13:53 UTC, babtshe commented on js/filter.js
> +  function neededFeatures() {
глагол

2020-11-10 13:53 UTC, babtshe commented on js/filter.js
> +      let isTypeMatched = typeElement.value === ANY ? true : element.offer.type === typeElement.value;
почему `let`?

2020-11-10 13:53 UTC, babtshe commented on js/filter.js
> +    return offers.filter(function (element) {
использование метода `filter` не подойдёт в данном случае так как он обрабатывает весь массив данных, а нам нужно найти только 5 подходящих элементов и после этого нет необходимости продолжать проверку массива.

2020-11-10 13:53 UTC, babtshe commented on js/filter.js
> +  }
модуль фильтрации ничего не должен знать про пины. Его задача принять массив входных данных и вернуть отфильтрованный массив.

2020-11-10 13:53 UTC, babtshe commented on js/mainPin.js
> +      // dragged = true;
❗

2020-11-10 13:53 UTC, babtshe commented on js/mainPin.js
> +      // }
❗

2020-11-10 15:26 UTC, babtshe approved these changes

2020-11-10 15:26 UTC, merged